/**
 * AI 분석 사유 코드 -> 사용자 문구 매핑
 */
export const REASON_LABELS: Record<string, string> = {
  INFO_ANALYSIS_OK: 'AI 판독이 정상 완료되어 기준을 충족했습니다.',
  MISSING_SLOT: '필수 항목이 누락되었습니다.',
  PARSE_FAILED: '문서 형식을 읽는 중 오류가 발생했습니다. 파일 형식/손상 여부를 확인해 주세요.',
  HEADER_MISMATCH: '필수 헤더 형식이 맞지 않습니다.',
  EMPTY_TABLE: '문서 내 데이터가 비어 있습니다.',
  UNIT_MISSING: '필수 단위 정보가 누락되어 수치를 확정할 수 없습니다.',
  EVIDENCE_MISSING: '근거 문서가 부족하여 판정 근거를 완성할 수 없습니다.',
  DATE_MISMATCH: '제출 기간 범위를 벗어난 데이터가 포함되어 있습니다.',
  NO_DATE_FOUND: '문서에서 기준 날짜를 확인하지 못했습니다.',
  SIGNATURE_MISSING: '확인 서명 또는 승인 정보가 없습니다.',
  OCR_FAILED: '문서 텍스트 판독이 어려웠습니다. 파일 선명도/방향을 확인해 주세요.',
  G_OCR_UNREADABLE: '문서 품질이 낮아 판독이 어렵습니다.',
  LLM_ANOMALY_DETECTED: '문서 내용에서 이상 징후가 감지되었습니다.',
  LLM_MISSING_FIELDS: '필수 정보 일부가 확인되지 않습니다.',
  VIOLATION_DETECTED: '준수 위반 가능성이 감지되었습니다.',
  WRONG_YEAR: '문서 대상 연도가 제출 기준과 다릅니다.',
  KEYWORD_MISSING: '필수 조항/핵심 키워드가 확인되지 않습니다.',
  DATA_NOT_FOUND: '필수 데이터 영역을 식별하지 못했습니다.',
  HIGH_RISK_DETECTED: '고위험 항목이 감지되었고 후속 조치 근거가 부족합니다.',
  MISSING_MANDATORY_TRAINING: '법정 의무 교육 항목 일부가 계획에서 확인되지 않습니다.',
  EDU_RATE_SPIKE: '교육 이수율이 이전 기간 대비 급격히 변동했습니다.',
  EDU_FUTURE_DATE: '교육일이 미래 날짜로 인식되었습니다.',
  RISK_OWNER_MISSING: '위험성평가 담당자 정보가 누락되었습니다.',
  RISK_CHECKDATE_MISSING: '위험성평가 점검일 정보가 누락되었습니다.',
  MISSING_SECTION_ORG: '조직/책임/권한 섹션이 확인되지 않습니다.',
  MISSING_SECTION_RISK: '위험성평가 섹션이 확인되지 않습니다.',
  MISSING_SECTION_INCIDENT: '사고 대응 절차 섹션이 확인되지 않습니다.',
  MISSING_SECTION_TRAINING: '교육/점검 섹션이 확인되지 않습니다.',
  MISSING_SECTION_IMPROVE: '개선조치 섹션이 확인되지 않습니다.',
  FIRE_ALL_GOOD_PATTERN: '점검 결과가 과도하게 동일하여 형식적 작성 가능성이 있습니다.',
  FIRE_COPYPASTE_PATTERN: '유사 문구 반복이 감지되어 복사 입력 가능성이 있습니다.',

  CROSS_HEADCOUNT_MISMATCH: '출석부 인원과 사진 인원이 일치하지 않습니다.',
  CROSS_ATTENDANCE_PARSE_FAILED: '출석부 인원 추출에 실패했습니다.',
  CROSS_PHOTO_COUNT_FAILED: '교육 사진에서 인원 식별이 어려웠습니다. 인물이 잘 보이도록 촬영해 주세요.',

  LOW_EDUCATION_RATE: '교육 이수율이 기준에 미달합니다.',
  EDU_DEPT_ZERO: '일부 부서의 이수율이 0%입니다.',
  RISK_ACTION_MISSING: '위험평가 조치 내용이 확인되지 않습니다.',
  E1_NEGATIVE_OR_ZERO: '사용량 수치에 0 또는 음수가 포함되어 데이터 확인이 필요합니다.',
  E1_DATE_PARSE_FAILED: '사용량 데이터의 날짜 형식을 해석하지 못했습니다.',
  E1_DUPLICATE_DATE: '동일 날짜의 중복 데이터가 감지되었습니다.',
  E1_GAP_DETECTED: '기간 중 누락 구간이 있어 연속성이 부족합니다.',
  E2_SPIKE_DETECTED: '사용량 급증/급감이 감지되어 원인 확인이 필요합니다.',
  E3_BILL_MISMATCH: '고지서 금액/사용량과 제출 데이터 합계가 일치하지 않습니다.',
  E3_BILL_PERIOD_UNCERTAIN: '고지서의 적용 기간을 명확히 식별하지 못했습니다.',
  E4_GHG_EVIDENCE_MISSING: '온실가스 산정 근거 문서가 부족합니다.',
  E5_MSDS_MISSING: '유해물질 목록 대비 MSDS 일부가 누락되었습니다.',
  E6_STOCK_SPIKE: '유해물질 재고 급증이 감지되어 확인이 필요합니다.',
  E6_INSPECTION_OVERDUE: '점검일 기준으로 정기 점검 지연이 의심됩니다.',
  E7_DISPOSAL_INCONSISTENT: '유해물질 폐기 내역 간 정합성이 맞지 않습니다.',
  E8_OLD_REVISION: '윤리강령 개정 이력이 오래되어 최신성 확인이 필요합니다.',
  E8_MISSING_SECTIONS: '윤리강령 필수 섹션 일부가 확인되지 않습니다.',
  E8_MULTI_VERSION: '서로 다른 버전 문서가 동시에 제출되어 기준 문서 확인이 필요합니다.',
  E9_NO_DISTRIBUTION_LOG: '윤리강령 배포/수신 확인 로그가 없습니다.',
  E9_NO_PLEDGE: '윤리 서약서가 확인되지 않습니다.',
  E9_PLEDGE_BEFORE_REVISION: '서약일이 개정일보다 빨라 구버전 서약 가능성이 있습니다.',
  E9_DISTR_BEFORE_REVISION: '배포일이 개정일보다 빨라 구버전 배포 가능성이 있습니다.',
};

export const getReasonLabel = (code: string): string => {
  return REASON_LABELS[code] ?? code;
};
